config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'search#index'

  resources :search, only: [:index, :create]
  resources :flights
  resources :buckets
  resources :cities
  resources :trips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  has_many :trips
  has_many :cities, through: :trips
end

app/models/city.rb
class City < ApplicationRecord
  has_many :trips
  has_many :buckets, through: :trips
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :city
  belongs_to :bucket
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  def index
    @buckets = Bucket.all
  end

  def show
    @bucket = Bucket.find(params[:id])
  end

  def new
    @bucket = Bucket.new
  end

  def create
    @bucket = Bucket.new(bucket_params)
    if @bucket.save
      flash[:info] = "Bucket Created!"
      redirect_to @bucket
    else
      render 'new'
    end
  end

  def edit
    @bucket = Bucket.find(params[:id])
  end

  def update
    @bucket = Bucket.find(params[:id])
    if @bucket.update_attributes(bucket_params)
      flash[:success] = "Bucket Updated!"
      redirect_to @bucket
    else
      render 'edit'
    end
  end

  def destroy
    Bucket.find(params[:id]).destroy
    flash[:success] = "Bucket deleted!"
    redirect_to buckets_url
  end


    private

      def bucket_params
        params.require(:bucket).permit(:name, :image_url)
      end


end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController


  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if @city.save
      flash[:info] = "City Created!"
      redirect_to @city
    else
      render 'new'
    end
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    if @city.update_attributes(city_params)
      flash[:success] = "City Updated!"
      redirect_to @city
    else
      render 'edit'
    end
  end

  def destroy
    City.find(params[:id]).destroy
    flash[:success] = "City deleted!"
    redirect_to cities_url
  end


  private

    def city_params
      params.require(:city).permit(:name, :country, :image_url, :bucket_id)
    end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index

    current_month = Time.now.strftime "%Y-%m"

    if params[:q] && !params[:q].empty?
      results = Skyscanner::Connection.browse_quotes({ :country => "US",
        :currency => "USD", :locale => "en-US", :originPlace => params[:q],
        :destinationPlace => "US", :outboundPartialDate => current_month,
        :inboundPartialDate => current_month })


      @quotes = results["Quotes"].sort_by {|price| price["MinPrice"]}
      @places = results["Places"]
      @carriers = results["Carriers"]
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @buckets = Bucket.all
    if params[:commit]
      redirect_to flights_path(q: params[:q])
    end
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      flash[:info] = "trip Created!"
      redirect_to @trip
    else
      render 'new'
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update_attributes(trip_params)
      flash[:success] = "trip Updated!"
      redirect_to @trip
    else
      render 'edit'
    end
  end

  def destroy
    Trip.find(params[:id]).destroy
    flash[:success] = "trip deleted!"
    redirect_to trips_url
  end


    private

      def trip_params
        params.require(:trip).permit(:city_id, :bucket_id)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/search_helper.rb
module SearchHelper

  def get_airport_data
    @get_airport_data ||=
    begin
      @airport_data = []

      airports = JSON.parse(File.read('app/public/airports.json'))
      airports.each do |a|
        @airport_data << Hash["label", a["iata"], "category", a["continent"]]
      end
    end

    @airport_data

  end

end

app/views/buckets/_form.html.erb
<%= form_for(@bucket) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/buckets/edit.html.erb
<div class="container">
<% provide(:button_text, 'Edit Bucket') %>
<h1 class="center">Edit Bucket <small><%= @bucket.name %></small></h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= render 'form' %>
  </div>
</div>
</div>

app/views/buckets/index.html.erb
<h1 class="center">Buckets</h1>

<div class="container-fluid" id="buckets">
  <div class="row">
    <div class="card-deck">

    <% @buckets.each do |bucket| %>
      <div class="card">
        <%= link_to (image_tag bucket.image_url,  class: "card-img-top"), bucket  %>
        <div class="card-block">
          <h4 class="card-title"><%= link_to bucket.name, bucket %></h4>
          <p class="card-subtitle"><%= link_to "Edit", edit_bucket_path(bucket) %></p>
        </div>
      </div>
    <% end %>


    </div>
  </div>
</div>

app/views/buckets/new.html.erb
<div class="container">
<% provide(:button_text, 'Create Bucket') %>
<h1 class="center">New Bucket</h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= render 'form' %>
  </div>
</div>
</div>

app/views/buckets/show.html.erb
<h1 class="center"><%= @bucket.name %></h1>

<div class="container" id="buckets">
  <div class="row">
    <div class="card-deck">


    <% @bucket.cities.each do |city| %>
      <div class="card">
        <%= link_to (image_tag city.image_url,  class: "card-img-top"), city  %>
        <div class="card-block">
          <h4 class="card-title"><%= link_to city.name, city %></h4>

          <p class="card-text"><strong><%= "Bucket".pluralize(city.buckets.count) %>:</strong>
            <% city.buckets.each do |bucket| %>
              <%= link_to bucket.name, bucket %>
            <% end %>
          </p>


          <p class="card-subtitle"><%= link_to "Edit", edit_city_path(city) %></p>
        </div>
      </div>
    <% end %>


    </div>
  </div>
</div>

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :country %>
  <%= f.text_field :country, class: "form-control" %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/cities/edit.html.erb
<div class="container">
<% provide(:button_text, 'Edit City') %>
<h1 class="center">Edit City<small> <%= @city.name %></small></h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= render 'form' %>
  </div>
</div>
</div>

app/views/cities/index.html.erb
<h1 class="center">Cities</h1>

<div class="container-fluid" id="buckets">
  <div class="row">
    <div class="card-deck">

    <% @cities.each do |city| %>
      <div class="card">
        <%= link_to (image_tag city.image_url,  class: "card-img-top"), city  %>
        <div class="card-block">
          <h4 class="card-title"><%= link_to city.name, city %></h4>
          <p class="card-subtitle"><%= link_to "Edit", edit_city_path(city) %></p>
        </div>
      </div>
    <% end %>


    </div>
  </div>
</div>

app/views/cities/new.html.erb
<div class="container">
<% provide(:button_text, 'Create City') %>
<h1 class="center">New City</h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= render 'form' %>
  </div>
</div>
</div>

app/views/cities/show.html.erb
<h1 class="center"><%= @city.name %></h1>


<div class="container" id="buckets">
  <div class="row">
    <div class="card-deck">
      <div class="card">
        <%= link_to (image_tag @city.image_url,  class: "card-img-top"), @city  %>
        <div class="card-block">
          <h4 class="card-title"><%= link_to @city.name, @city %></h4>

          <p class="card-text"><strong><%= "Bucket".pluralize(@city.buckets.count) %>:</strong>
            <% @city.buckets.each do |bucket| %>
              <%= link_to bucket.name, bucket %>
            <% end %>
          </p>


          <p class="card-subtitle"><%= link_to "Edit", edit_city_path(@city) %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flights/_results.html.erb
 <div id="flight_results">
  <h1 class="center">Flights from <%= params[:q].upcase %> to USA This Month</h1>
  <p class="pull-left">Showing first 50 results.</p>

  <% count = 0 %>

  <% while count < 50 %>
    <div class="container-fluid">
      <div class="row">
        <div class="card-deck">
          <% @quotes[count,3].each do |result| %>
            <% place = @places.find {|place| place["PlaceId"] == result["OutboundLeg"]["DestinationId"] } %>
            <% in_flight = @carriers.find {|carrier| carrier["CarrierId"] == result["OutboundLeg"]["CarrierIds"].first } %>

            <% if result["MinPrice"].to_i < 300 %>
              <% price_color = "success" %>
            <% elsif result["MinPrice"].to_i < 500 %>
              <% price_color = "warning" %>
            <% else %>
              <% price_color = "danger" %>
            <% end %>

            <div class="card card-outline-<%= price_color %>">
              <%= image_tag "https://placehold.it/150x100",  class: "card-img-top"  %>
              <div class="card-block">

                <h4 class="card-title"><%= place["CityName"] %></h4>
                <h6 class="card-subtitle text-<%= price_color %>">$<%= result["MinPrice"].to_i %>.00</h6>
                <p class="card-text"><%= in_flight %></p>

                <p class="card-text">This flight arrives into <%= place["Name"] %>.</p>

                <p class="card-text">
                  <small class="text-muted"><strong>Depart: </strong><%= result["OutboundLeg"]["DepartureDate"].to_date.strftime("%A, %B %d %Y")%></small> <br />
                  <small class="text-muted"><strong>Return: </strong><%= result["InboundLeg"]["DepartureDate"].to_date.strftime("%A, %B %d %Y")%></small></p>
              </div>
            </div>
          <% end %>

          <% count += 3 %>

        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flights/index.html.erb
<% if @quotes %>
  <%= render "results" %>
<% else %>
<div class="alert alert-warning" role="alert">
  <strong>Warning!</strong> Yikes! Looks like we couldn't find any quotes, or you searched an invalid Airport Code!
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anyfare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>

  <body>
    <% if request.original_url == search_index_path || root_url %>
        <%= yield %>
    <% else %>
      <div class="container-fluid">
        <%= yield %>
      </div>
    <% end %>
  </body>
</html>

app/views/search/_buckets.html.erb
<div class="container-fluid" id="buckets">
    <div class="row">
      <div class="card-deck">


          <div class="card">
            <%= image_tag "http://i.imgur.com/d8WRiYd.jpg",  class: "card-img-top"  %>
            <div class="card-block">
              <h4 class="card-title">Beaches</h4>
              <h6 class="card-subtitle"">Bucket</h6>
              <p class="card-text">Bucket</p>
            </div>
          </div>
          <div class="card">
            <%= image_tag "http://i.imgur.com/Ek5NOJA.jpg",  class: "card-img-top"  %>
            <div class="card-block">
              <h4 class="card-title">Cities</h4>
              <h6 class="card-subtitle"">Bucket</h6>
              <p class="card-text">Bucket</p>
            </div>
          </div>
          <div class="card">
            <%= image_tag "http://i.imgur.com/tGMqjLw.jpg",  class: "card-img-top"  %>
            <div class="card-block">
              <h4 class="card-title">Mountains</h4>
              <h6 class="card-subtitle"">Bucket</h6>
              <p class="card-text">Bucket</p>
            </div>
          </div>

      </div>
    </div>
  </div>

app/views/search/_form.html.erb
<%= form_tag("/flights", method: "get", class: "form-inline") do %>
  <div class="form-group">
    <%= text_field_tag :q, nil, placeholder: 'Airport Code', class: "form-control", id: "airport-search-input" %>
    <%= button_tag(type: "submit", class: "btn btn-primary") do %>
      <i class="fa fa-plane"></i>&nbsp; Take me anywhere!
    <% end %>
  </div>
<% end %>

app/views/search/index.html.erb
<div class="site-wrapper">

  <div class="site-wrapper-inner">

    <div class="cover-container">

      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">Anyfare</h3>
          <nav class="nav nav-masthead">
            <%= link_to "Home", root_url, class: "nav-link active" %>
            <%= link_to "Destinations", buckets_path, class: "nav-link" %>
          </nav>
        </div>
      </div>

      <div class="inner cover">
        <h1 class="cover-heading">Anyfare. Anywhere.</h1>
        <p class="lead">Ready to get away? Anyfare helps you find the best last minute flights to popular getaway destinations. Whether you're looking to relax on the beach or hit the slopes, we'll make finding flights easy and affordable!</p>
        <p class="lead">
          <%= render "form" %>
        </p>
      </div>

      <div class="row">
        <%= render "buckets" %>
      </div>

      <div class="mastfoot">
        <div class="inner">
          <p>Concept by  <a href="http://justinwhite.co">Justin White</a> and <a href="https://www.linkedin.com/in/carl-eric-girardin-9392b266">Carl-Eric Girardin</a>.</p>
        </div>
      </div>

    </div>

  </div>

</div>




<% get_airport_data %>

<%= javascript_tag do %>
  var airport_data = $.parseJSON('<%=j @airport_data.to_json.html_safe %>');
<% end %>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>

  <%= f.label :city %>
  <%= f.select :city_id, City.all.collect{|city| [city.name, city.id]}, class: "form-control" %> <br />

  <%= f.label :bucket %>
  <%= f.select :bucket_id, Bucket.all.collect{|bucket| [bucket.name, bucket.id]}, class: "form-control" %>

  <br />

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/trips/edit.html.erb
<div class="container">
<% provide(:button_text, 'Edit Trip') %>
<h1 class="center">Edit Trip<small> <%= @trip.id %></small></h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= render 'form' %>
  </div>
</div>
</div>

app/views/trips/index.html.erb
<h1 class="center">Trips</h1>

<div class="container-fluid" id="buckets">
  <div class="row">
    <div class="card-deck">

    <% @trips.each do |trip| %>
      <div class="card">
        <%= link_to (image_tag "placehold.it/350x350",  class: "card-img-top"), trip  %>
        <div class="card-block">
          <h4 class="card-title"><%= link_to trip.id, trip %></h4>
          <p class="card-subtitle"><%= link_to "Edit", edit_trip_path(trip) %></p>
        </div>
      </div>
    <% end %>


    </div>
  </div>
</div>

app/views/trips/new.html.erb
<div class="container">
<% provide(:button_text, 'Create Trip') %>
<h1 class="center">New Trip</h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= render 'form' %>
  </div>
</div>
</div>

app/views/trips/show.html.erb
<h1 class="center">Trip ID: <%= @trip.id %></h1>

<strong>Bucket:</strong> <%= Bucket.find(@trip.bucket_id).name %> <br />
<strong>City:</strong> <%= City.find(@trip.city_id).name %> <br />

<%= link_to "Edit", edit_trip_path(@trip) %>